[package]
name = "miko_os"
version = "0.1.0"
authors = ["MathxH Chen <brainfvck@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"